name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint Check
        run: |
          make lint
      - uses: psf/black@stable
        with:
          src: "./goblet"
          version: "23.1.0"

  Test:
    runs-on: ubuntu-latest
    needs: Lint
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Test Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest & goblet
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          pip install requests-mock
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          export PYTHONPATH=$(pwd)
          export X_GOBLET_LOCAL=true
          export G_MOCK_CREDENTIALS=True
          export G_TEST_DATA_DIR=$PWD/goblet/tests/data/http
          export G_TEST_PROJECT_ID="goblet"
          coverage run -m pytest goblet/tests;
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
